"""
PatientPyDriver.py
version 1.1
package PatientPy
Created by AndrewJKing.com

This file instantiates a patientpy feature vector based on the input parameters. 
Input parameters include:
feature directory -> as populated by create_feauture_vectors.py
output directory -> where the resulting feature vector should be saved
output file root -> the filename root for the resulting feature vector. Will have fold numbers appended to it if folds are used.
Features types to include -> list of the feature types to include (must be in the form created by create_feature_vectors.py) [1]
Additional feature files -> additional features to include, i.e. ones not generated by create_feature_vectors. [2]
Number of folds -> The number of folds to use. If not set, a single fold containing all the data will be used. 
Use stratified folds -> If true, the folds will be stratified based on the targets

[Notes]
[1] for each feature type NAME -> a folder NAME_feature_files and a file NAME_feature_columns where the rows in the file correspond to the columns in each of the feature files. Look at example in resources
[2] for each additional feature NAME -> a feature file called NAME_features and a file called NAME_feature_columns. The same correspondence as Note 1. 


---DEPENDENCIES---
Must run patient_pickler first to store data structures that are used here.
^ set pkl_dir to the same value as was used in patient_pickler.
Must create a feature directory.
^The following subdirectories must be created as well: 'root_data/','med_data/','procedure_data/','micro_data/','io_data/','demo_data/'
Must create labeled_case_list file and linked participant_info files. See resource folder for examples. 
"""
